(source "jcs-elpa")
(source "melpa")

(package "eldoc-meta-net" "0.1.0" "Eldoc support for meta-net")

(package-file "eldoc-meta-net.el")

(depends-on "emacs" "26.1")
(depends-on "meta-net")
(depends-on "ht")
(depends-on "csharp-mode")

(development
 (depends-on "ert-runner"))

(setq network-security-level 'low      ; see https://github.com/jcs090218/setup-emacs-windows/issues/156#issuecomment-932956432
      byte-compile-error-on-warn nil)
